### ISSUE TITLE
Add a frontend way to view non-verbose error messages for services

### ISSUE THREAD

**Issue by AidanFeess** [LTSEC/scoring-engine#56]
For newer blue teams, it might be helpful for them to see non-verbose error message relating to services. They would be able to see these on the website, and it would look something like this:

```yaml
{
  service: db
  ip: 192.168.0.11
  port: 3306
  user: maria
  state: failed
  msg: "Connection refused"
}
```
